### ISSUE TITLE
Invoice email should have who is owed money

### ISSUE THREAD

**Issue by briandoyle81** [Lambda-School-Labs/CS8-payme#48]
Please update the email so that it says "Our records are showing that you have an outstanding invoice with [Company Name] in the amount of:"

**Comment by DragonRydrz** [comment]
User model is updated to now have a `fullName` and `companyName`.  This will allow the `companyName` to be used in the email (if there is one associated with the user).  If no `companyName` is associated with the user, `fullName` can be used instead.

**Comment by Dbald** [comment]
I changed it and everything is pushed.
